# Generated by Django 4.2.7 on 2023-11-30 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='questoin',
            new_name='question',
        ),
    ]
